name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
      - name: Install depedencies
        run: npm install
      
      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Run publish
        run: echo ${{ secrets.IS_WORK }}
        run: npm install -g npm-cli-login && npm-cli-login -u ${{NPM_USER}} -p ${{NPM_PASS}} -e ${{NPM_EMAIL}}
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc && npm publish --access public
