name: CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install depedencies
        run: npm install
      
      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Run publish
        run: |
          echo ${{ secrets.IS_WORK }}
          npm install npm-cli-login && npm npm-cli-login -u ${{secrets.NPM_USER}} -p ${{secrets.NPM_PASS}} -e ${{secrets.NPM_EMAIL}}
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc && npm publish --access public
