name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tests
        run: npm run test

      # Runs a set of commands using the runners shell
      - name: Build
        run: npm install && npm build
