name: CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install depedencies
        run: npm install
      
      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Run publish
        run: |
          yarn npm-cli-login -u ${{secrets.NPM_AUTH_USER}} -p ${{secrets.NPM_AUTH_PASS}} -e ${{secrets.NPM_AUTH_EMAIL}}
          npm publish --access public
